name: Publish Hugo Site

on:
  push:
    branches:
      - main
      - master
      

jobs:
  update_hugo_npm_dependencies:
    name: Update Hugo npm Dependencies
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true

      - name: Write composite package.json
        run: hugo mod npm pack

      - name: Install npm Packages
        run: npm install




  publish:
    name: Publish Hugo Site
    needs: update_hugo_npm_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          ref: ${{ needs.update_hugo_npm_dependencies.outputs.commit_hash }}

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true

      - name: Install npm Packages
        run: npm ci

      - name: Build Hugo
        run: hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            branch: gh-pages
            folder: public
            token: ${{ secrets.ACCESSTOKEN }}
            # clean: true
            single-commit: true
